/**
 * Standard event taxonomy for the frint3d platform.
 *
 * All `track(...)` calls should use one of these names. Adding a new event:
 *   1. Add to EVENTS const below
 *   2. Document expected `properties` shape in EventProperties (if non-trivial)
 *   3. Use it via `track(EVENTS.NEW_NAME, { ... })`
 */

export const EVENTS = {
  // Auth
  USER_SIGNUP: "USER_SIGNUP",
  USER_LOGIN: "USER_LOGIN",
  USER_LOGIN_FAILED: "USER_LOGIN_FAILED",
  USER_LOGOUT: "USER_LOGOUT",
  USER_PROFILE_UPDATED: "USER_PROFILE_UPDATED",
  USER_PASSWORD_CHANGED: "USER_PASSWORD_CHANGED",

  // Payments (orders)
  ORDER_CREATED: "ORDER_CREATED",
  ORDER_STATUS_CHANGED: "ORDER_STATUS_CHANGED",
  PAYMENT_INITIATED: "PAYMENT_INITIATED",
  PAYMENT_CALLBACK_RECEIVED: "PAYMENT_CALLBACK_RECEIVED",
  PAYMENT_VERIFIED: "PAYMENT_VERIFIED",
  PAYMENT_DENIED: "PAYMENT_DENIED",
  PAYMENT_DUPLICATE: "PAYMENT_DUPLICATE",

  // Slicing
  SLICE_UPLOADED: "SLICE_UPLOADED",
  SLICE_QUEUED: "SLICE_QUEUED",
  SLICE_DONE: "SLICE_DONE",
  SLICE_FAILED: "SLICE_FAILED",
  SLICE_CACHE_HIT: "SLICE_CACHE_HIT",

  // Meshy AI
  MESHY_JOB_STARTED: "MESHY_JOB_STARTED",
  MESHY_JOB_DONE: "MESHY_JOB_DONE",
  MESHY_JOB_FAILED: "MESHY_JOB_FAILED",
  MESHY_TASK_SUBMITTED: "MESHY_TASK_SUBMITTED",
  MESHY_REFUND_ISSUED: "MESHY_REFUND_ISSUED",

  // Designs
  DESIGN_SUBMITTED: "DESIGN_SUBMITTED",
  DESIGN_APPROVED: "DESIGN_APPROVED",
  DESIGN_REJECTED: "DESIGN_REJECTED",
  DESIGN_PUBLISHED: "DESIGN_PUBLISHED",
  DESIGN_REVIEW_CREATED: "DESIGN_REVIEW_CREATED",
  DESIGN_REVIEW_UPDATED: "DESIGN_REVIEW_UPDATED",
  DESIGN_REVIEW_DELETED: "DESIGN_REVIEW_DELETED",
  DESIGN_REVIEW_HIDDEN: "DESIGN_REVIEW_HIDDEN",
  DESIGN_REVIEW_RESTORED: "DESIGN_REVIEW_RESTORED",

  // Credits
  CREDIT_PURCHASE_INITIATED: "CREDIT_PURCHASE_INITIATED",
  CREDIT_PURCHASE_COMPLETED: "CREDIT_PURCHASE_COMPLETED",
  CREDITS_SPENT: "CREDITS_SPENT",
  CREDITS_REFUNDED: "CREDITS_REFUNDED",

  // Cart
  CART_ITEM_ADDED: "CART_ITEM_ADDED",
  CART_CHECKOUT_STARTED: "CART_CHECKOUT_STARTED",
} as const;

export type EventName = (typeof EVENTS)[keyof typeof EVENTS];
