/**
 * POST /api/internal/thumbnail/[designId]
 *
 * Internal-only endpoint called by the headless renderer (worker side, via
 * the page at /_render/design/[id]). Saves the captured PNG to storage and
 * updates Design.thumbnailUrl + thumbnailGeneratedAt.
 *
 * Auth: shared secret in Authorization: Bearer <token> matching
 * INTERNAL_RENDERER_TOKEN. No user session.
 *
 * Idempotency: writes are conditional — if a thumbnail already exists and
 * was generated by the renderer (not a manual upload), we silently overwrite
 * (admin re-render scenario). If it was a manual upload, we keep the manual
 * one. Manual = thumbnailUrl set but thumbnailGeneratedAt null.
 */
import { NextResponse } from "next/server";
import { prisma } from "@/lib/db";
import { saveUpload } from "@/lib/storage";
import { logError } from "@/lib/observability";

export const runtime = "nodejs";
export const dynamic = "force-dynamic";

const TOKEN = process.env.INTERNAL_RENDERER_TOKEN ?? "";
const MAX_DATA_URL_BYTES = 8 * 1024 * 1024; // ~6MB PNG → 8MB base64

export async function POST(
  req: Request,
  { params }: { params: Promise<{ designId: string }> },
) {
  if (!TOKEN) {
    return NextResponse.json(
      { error: "INTERNAL_RENDERER_TOKEN not configured" },
      { status: 503 },
    );
  }
  const auth = req.headers.get("authorization") ?? "";
  if (auth !== `Bearer ${TOKEN}`) {
    return NextResponse.json({ error: "forbidden" }, { status: 403 });
  }

  const { designId } = await params;

  let body: { dataUrl?: unknown };
  try {
    body = (await req.json()) as { dataUrl?: unknown };
  } catch {
    return NextResponse.json({ error: "invalid json" }, { status: 400 });
  }
  const dataUrl = body.dataUrl;
  if (typeof dataUrl !== "string" || !dataUrl.startsWith("data:image/png;base64,")) {
    return NextResponse.json({ error: "expected png data url" }, { status: 400 });
  }
  if (dataUrl.length > MAX_DATA_URL_BYTES) {
    return NextResponse.json({ error: "image too large" }, { status: 413 });
  }

  const base64 = dataUrl.slice("data:image/png;base64,".length);
  const bytes = Buffer.from(base64, "base64");

  // Manual override guard: if a human uploaded a thumbnail, don't overwrite.
  // (Manual uploads have thumbnailUrl set but thumbnailGeneratedAt null.)
  const current = await prisma.design.findUnique({
    where: { id: designId },
    select: { thumbnailUrl: true, thumbnailGeneratedAt: true },
  });
  if (!current) {
    return NextResponse.json({ error: "design not found" }, { status: 404 });
  }
  if (current.thumbnailUrl && !current.thumbnailGeneratedAt) {
    return NextResponse.json({ ok: true, skipped: "manual-thumbnail" });
  }

  try {
    const saved = await saveUpload(
      "thumbnail",
      `design-${designId}.png`,
      bytes,
    );
    await prisma.design.update({
      where: { id: designId },
      data: {
        thumbnailUrl: saved.key,
        thumbnailGeneratedAt: new Date(),
      },
    });
  } catch (e) {
    await logError(e, {
      source: "api:internal:thumbnail",
      severity: "MEDIUM",
      metadata: { designId },
    });
    return NextResponse.json({ error: "save failed" }, { status: 500 });
  }

  return NextResponse.json({ ok: true });
}
